REM AUTHOR: KALYAN RAPARTHI, KALYAN.RAPATHI@HOTMAIL.COM, GITHUB: KALYAN-RAPARTHI
REM THIS SCRIPT INSTALLS HTTPX ON WINDOWS.

REM POWERSHELL -COMMAND "INVOKE-WEBREQUEST -URI 'HTTPS://RAW.GITHUBUSERCONTENT.COM/KALYAN-RAPARTHI/HTTPX/REFS/HEADS/MAIN/INSTALL/INSTALL.CMD' -OUTFILE 'C:\PROGRAM FILES\HTTPX\INSTALL.CMD'"

@ECHO OFF
REM CHECK FOR ADMINISTRATIVE PRIVILEGES
OPENFILES >NUL 2>&1

IF %ERRORLEVEL% NEQ 0 (
    ECHO THIS SCRIPT REQUIRES ADMINISTRATIVE PRIVILEGES. PLEASE RUN AS ADMINISTRATOR.
    EXIT /B 1
)
`
REM DOWNLOAD HTTPX FROM GITHUB
ECHO DOWNLOADING HTTPX FROM GITHUB
POWERSHELL -COMMAND "INVOKE-WEBREQUEST -URI 'HTTPS://GITHUB.COM/KALYAN-RAPARTHI/HTTPX/RAW/REFS/HEADS/MAIN/BIN/HTTPX_WIN64_0.1.0.EXE' -OUTFILE 'C:\PROGRAM FILES\HTTPX\HTTPX.EXE'"
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: FAILED TO DOWNLOAD HTTPX.
    EXIT /B 1
)

REM INSTALL HTTPX
ECHO INSTALLING HTTPX
POWERSHELL -COMMAND "INVOKE-WEBREQUEST -URI 'HTTPS://GITHUB.COM/KALYAN-RAPARTHI/HTTPX/RAW/REFS/HEADS/MAIN/INSTALL/WIN64_INSTALLER_0.1.0.EXE' -OUTFILE 'C:\PROGRAM FILES\HTTPX\WIN64_INSTALLER_0.1.0.EXE'"
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: FAILED TO DOWNLOAD INSTALLER.
    EXIT /B 1
)

REM ADD HTTPX TO SYSTEM PATH
ECHO ADDING HTTPX TO SYSTEM PATH...
SETX PATH "%PATH%;C:\PROGRAM FILES\HTTPX"
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: FAILED TO ADD HTTPX TO SYSTEM PATH.
    EXIT /B 1
)

ECHO INSTALLATION COMPLETE.
PAUSE